#!/usr/bin/env bash
# repo_facts.sh — emit verified repo state for a handoff's Current Progress section.
#
# Why this exists: the state of the repo (branch, what's committed, what's still
# dirty) is the part of a handoff that most often turns out wrong, because the
# author writes it from memory at the end of a long session. This script reads
# it from git instead, so there is nothing to misremember. Run it, then paste
# the output verbatim into Current Progress and write the narrative around it.
#
# Usage: repo_facts.sh [path-to-repo]   (defaults to CWD)

set -euo pipefail

repo="${1:-$(pwd)}"
cd "$repo" 2>/dev/null || { echo "_repo_facts: cannot cd to ${repo}_"; exit 0; }

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "_repo_facts: $repo is not a git repository — describe progress manually and verify each file path with Read/Glob._"
  exit 0
fi

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '(detached)')"
dirty="$(git status --short 2>/dev/null)"
stat="$(git diff --stat 2>/dev/null)"
staged="$(git diff --cached --stat 2>/dev/null)"

echo "### Verified repo state"
echo "_Generated by repo_facts.sh from git — base Current Progress on this, do not overwrite from memory._"
echo
echo "- **Branch:** \`$branch\`"

if [ -z "$dirty" ]; then
  echo "- **Working tree:** clean (no uncommitted changes)"
else
  count="$(printf '%s\n' "$dirty" | grep -c . || true)"
  echo "- **Uncommitted changes:** $count path(s)"
  printf '%s\n' "$dirty" | sed 's/^/  - `/; s/$/`/'
fi

if [ -n "$stat" ]; then
  echo "- **Unstaged diff (\`git diff --stat\`):**"
  printf '%s\n' "$stat" | sed 's/^/  /'
fi
if [ -n "$staged" ]; then
  echo "- **Staged diff (\`git diff --cached --stat\`):**"
  printf '%s\n' "$staged" | sed 's/^/  /'
fi

echo "- **Recent commits (\`git log --oneline -10\`):**"
git log --oneline -10 2>/dev/null | sed 's/^/  - /' || echo "  - (no commits)"
